language: julia
julia:
  - 1

jobs:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl skiplinks
      name: "HTML"
      after_success: skip