name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest]
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        env:
          PYTHON: # remove PYTHON env variable to make sure packages are installed
      - uses: julia-actions/julia-runtest@master